### PR TITLE
Change Merity's citation to ours

### PR DESCRIPTION
**Pull request by daemon**

### CODE REVIEW

**Review by achyudh — APPROVED** [review]

**Comment by achyudh** [comment]
LGTM.

**Comment by Ashutosh-Adhikari** [comment]
Should we wait till it appears on ACL anthology?

**Comment by daemon** [comment]
We can change it when it comes out on ACL anthology. I think it'd be nice for the incoming people to read it.

**Comment by Ashutosh-Adhikari** [comment]
makes sense! Go ahead and merge it?

**Pull request merged**
